"""empty message

Revision ID: 34ab1fb34827
Revises: dccfd0a824b4
Create Date: 2025-04-30 10:26:01.013684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ab1fb34827'
down_revision = 'dccfd0a824b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('postcode')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile')
        batch_op.drop_column('dob')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
