"""Add visualization support fields

Revision ID: 9edc99de42ee
Revises: e5c189251f88
Create Date: 2025-05-01 04:22:37.456360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edc99de42ee'
down_revision = 'e5c189251f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('has_geo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_time', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sharing_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('sharing_status')
        batch_op.drop_column('has_time')
        batch_op.drop_column('has_geo')
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
